spring:
  profiles:
    active: pre

logging:
  level:
    '[org.springframework]': INFO
    '[com.daniel.hundirflota]': TRACE
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level - %msg%n'
  file.name: logs/testing-executor.log

jwt-config:
  secret-key: 'D679BBFB6B5BDA4C65DC54634D6F2D1C1D3A2B645D8DA4704468E334E4C7CAB4'