spring:
  sql:
    init:
      platform: postgres 
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/Battleship
    username: postgres
    password: daniel    
    driverClassName: org.postgresql.Driver
  profiles:
    active: pre
  
logging:
  level:
    '[org.springframework]': INFO
    '[com.daniel.hundirflota]': INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level - %msg%n'
  file.name: logs/executor.log

jwt-config:
  secret-key: 'D679BBFB6B5BDA4C65DC54634D6F2D1C1D3A2B645D8DA4704468E334E4C7CAB4'